### ISSUE TITLE
Logger

### ISSUE THREAD

**Issue by giospada** [EndPass-Game/programmazione#2]
Il Logger, deve essere una interfaccia facile da utilizzare che scriva delle informazioni su un file, per esempio chiamando semplicemente il comando `log` e deve essere una specie di wrapper per la funzione fprintf, quindi deve accettare parametri in una maniera simile a questa `log("prova %d",11)` deve dare una cosa tipo 

```text
-- Class:34 ; prova 11

```

**Comment by Flecart** [comment]
fatto con #18
